'use strict';
/* =========================================================
 * 赛博安全学院 — 安全知识手册 (小型教材)
 * 用法:
 *   docs              目录
 *   docs <章节号>      阅读章节
 *   docs term <词>    查术语表
 *   docs search <词>  全文检索
 * ========================================================= */

const DOCBOOK = [
  {
    n: 1, title: '安全世界观与职业路径',
    lines: [
      '══ 安全是什么?',
      '  信息安全 = 保护信息的机密性 (Confidentiality)、完整性 (Integrity)、可用性 (Availability) —— CIA 三元组。',
      '  机密性: 只有该看的人能看 (加密/权限)',
      '  完整性: 数据没被篡改 (哈希/签名)',
      '  可用性: 该用的时候能用 (备份/抗DDoS)',
      '',
      '══ 红队 vs 蓝队',
      '  红队: 模拟攻击者 (渗透测试/漏洞利用) — 发现问题',
      '  蓝队: 防御者 (监控/响应/取证/加固) — 解决问题',
      '  紫队: 红蓝配合, 攻防演练互相提升',
      '',
      '══ 威胁模型',
      '  资产 (Assets): 什么值得保护? (数据/系统/声誉)',
      '  威胁 (Threats): 谁想害你? (黑客/内鬼/自然灾害)',
      '  漏洞 (Vulnerabilities): 哪里能被打?',
      '  风险 = 威胁 × 漏洞 × 资产价值',
      '',
      '══ 职业路径 (参考)',
      '  红队: 渗透测试 → 红队/漏洞研究 → 安全架构师',
      '  蓝队: SOC 分析师 → 应急响应/威胁狩猎 → 安全运营负责人',
      '  开发: DevSecOps → 应用安全 → 安全产品研发',
      '  管理: 安全审计/合规 → 安全总监 (CISO)',
      '  证书: OSCP (实战渗透) / CEH / CISSP / CISP / 云安全 (CCSP)',
      '',
      '══ 伦理铁律',
      '  1. 只测授权目标  2. 不破坏不窃取  3. 漏洞负责任披露  4. 能力越大责任越大',
    ],
  },
  {
    n: 2, title: '网络基础手册',
    lines: [
      '══ IP 地址',
      '  IPv4: 32 位, 4 段 0-255, 如 10.0.2.7',
      '  私有网段: 10.x.x.x / 172.16-31.x.x / 192.168.x.x (内网用)',
      '  127.0.0.1 = 本机 (localhost)',
      '  IPv6: 128 位, 如 fe80::1',
      '',
      '══ 端口 (0-65535)',
      '  21 FTP  |  22 SSH  |  23 Telnet  |  25 SMTP  |  53 DNS',
      '  80 HTTP |  110 POP3 |  135 RPC |  139/445 SMB |  443 HTTPS',
      '  1433 MSSQL |  3306 MySQL |  3389 RDP |  5432 PostgreSQL',
      '  6379 Redis |  8080 HTTP代理/备站 |  9200 Elasticsearch',
      '  高危/后门常见: 1337 31337 4444 666 6666 8000',
      '',
      '══ TCP 三次握手',
      '  SYN → SYN-ACK → ACK。扫描器发 SYN, 收到 SYN-ACK = 端口开放。',
      '  UDP 无握手: 发数据, 有回应=开放 (扫描更不可靠)。',
      '',
      '══ 常见协议',
      '  DNS: 域名→IP (53, UDP/TCP)',
      '  HTTP/HTTPS: 网页 (80/443)',
      '  SSH: 加密远程登录 (22)',
      '  FTP: 文件传输 (21 控制/20 数据), 明文!',
      '  SMB: Windows 文件共享 (445), 永恒之蓝攻击面',
      '  RDP: Windows 远程桌面 (3389)',
      '  ICMP: ping 用 (网络可达性)',
      '',
      '══ 网络工具',
      '  ping: 测试连通  |  nslookup/dig: DNS 查询',
      '  nc (netcat): 瑞士军刀 (连端口/传文件/反弹shell)',
      '  curl/wget: HTTP 客户端  |  traceroute: 路由追踪',
      '  nmap: 扫描之王  |  tcpdump/Wireshark: 抓包',
      '  whois: 域名信息  |  crt.sh: 证书透明日志找子域',
    ],
  },
  {
    n: 3, title: '密码学手册',
    lines: [
      '══ 三个概念 (必考)',
      '  编码: 换表示, 无密钥可逆 (Base64/Hex/URL编码)',
      '  加密: 密钥打乱, 对称/非对称',
      '  哈希: 单向指纹, 不可逆 (MD5/SHA/bcrypt)',
      '',
      '══ 对称加密',
      '  同一个密钥加密和解密。快, 但密钥怎么安全给对方?',
      '  代表: AES (现代标准), DES/3DES (已废)',
      '',
      '══ 非对称加密',
      '  公钥加密/私钥解密 (反之签名)。解决密钥分发问题。',
      '  代表: RSA, ECC (椭圆曲线)。HTTPS 握手时用。',
      '',
      '══ 哈希速查',
      '  MD5: 32 位 hex — 已破, 勿用于安全 (碰撞+彩虹表)',
      '  SHA-1: 40 位 hex — 已破 (SHAttered 碰撞)',
      '  SHA-256: 64 位 hex — 当前主流',
      '  bcrypt/argon2/scrypt: 慢哈希, 存密码首选',
      '',
      '══ 攻击哈希',
      '  字典攻击: 常用密码表 (rockyou 1400 万条)',
      '  暴力: 穷举组合  |  彩虹表: 预计算哈希表',
      '  加盐: 每个用户随机 salt → 彩虹表失效',
      '',
      '══ 密码强度',
      '  长度 > 复杂度。12 位随机 > 8 位带符号',
      '  密码管理器 + 双因素认证 (MFA) 是最佳实践',
      '',
      '══ 经典密码 (游戏 L2)',
      '  凯撒: 字母平移 N  |  ROT13: 平移 13',
      '  维吉尼亚: 密钥循环位移  |  XOR: 位运算, 同一操作加解密',
    ],
  },
  {
    n: 4, title: 'Web 安全手册',
    lines: [
      '══ HTTP 速查',
      '  方法: GET/POST/PUT/DELETE/OPTIONS',
      '  状态码: 200 成功 | 301/302 跳转 | 403 禁止 | 404 无 | 500 服务器错',
      '  头: Cookie/Referer/User-Agent/Content-Type/Authorization',
      '',
      '══ OWASP Top 10 (2021)',
      '  A01 失效访问控制 (IDOR/越权)   A02 加密失败',
      '  A03 注入 (SQLi/命令注入)        A04 不安全设计',
      '  A05 安全配置错误                A06 易受攻击组件',
      '  A07 身份识别失败                A08 完整性失效 (供应链)',
      '  A09 日志监控不足                A10 SSRF',
      '  (2021 为经典框架; 2025 版已更新, 原理一致。)',
      '',
      '══ SQL 注入',
      '  根因: 输入拼进 SQL。经典载荷:',
      '    admin\'--          引号闭合+注释',
      '    \' OR \'1\'=\'1\' --    恒真绕过',
      '    UNION SELECT ...   联表注数据',
      '  防御: 参数化查询 (唯一正确解法)',
      '',
      '══ XSS',
      '  反射/存储/DOM 三型。危害: 窃取 Cookie 劫持会话。',
      '  载荷: <script>alert(1)</script>, <img src=x onerror=alert(1)>',
      '  防御: 输出转义 + CSP + HttpOnly Cookie',
      '',
      '══ 认证与会话',
      '  Cookie/Session: 偷到 = 登录了。JWT: 签名令牌。',
      '  攻击: 会话固定/劫持、JWT 弱密钥伪造 (alg:none)',
      '  防御: HttpOnly+Secure+SameSite、MFA、登录后换 session id',
      '',
      '══ 其它高频漏洞',
      '  命令注入: 输入拼进 shell (防御: 禁拼 shell)',
      '  路径穿越: ../ 读取任意文件 (防御: 规范化+白名单目录)',
      '  IDOR: 改 id 越权 (防御: 对象级授权检查)',
      '  文件上传: 不校验类型=webshell (防御: 白名单+重命名+禁用执行)',
      '  CSRF: 诱导浏览器带 Cookie 发请求 (防御: CSRF Token)',
      '  SSRF: 服务器访问任意地址 (防御: 白名单)',
      '  XXE: XML 外部实体 (防御: 禁用外部实体)',
      '  反序列化: 恶意对象注入 (防御: 白名单类)',
    ],
  },
  {
    n: 5, title: '系统与权限手册',
    lines: [
      '══ Linux 权限',
      '  root (uid 0) vs 普通用户; 组 (group) 批量授权',
      '  文件权限 rwx 三组位: rwxr-xr-x (属主/组/其他)',
      '  查看: ls -l; 修改: chmod/chown',
      '',
      '══ Linux 提权路径',
      '  sudo 错误配置: sudo -l 查看; find/vim/python 可逃逸',
      '  SUID: find / -perm -4000 2>/dev/null',
      '  弱凭据/历史记录: .bash_history, 配置文件明文',
      '  计划任务: cron 以 root 跑可写脚本',
      '  内核漏洞: uname -a → 查 CVE → 公开 exploit',
      '',
      '══ Windows 提权路径',
      '  服务路径可写: 替换服务程序 → SYSTEM',
      '  Potato 家族: SeImpersonate → SYSTEM',
      '  mimikatz: 内存 dump 明文密码/哈希 → 哈希传递',
      '  UAC 绕过: 白名单程序触发高权限',
      '',
      '══ 常见服务口令 (默认/弱)',
      '  admin/admin, root/toor, admin/123456, guest/guest',
      '  数据库: root/root, sa/123456; Redis 无密码',
      '',
      '══ 加固清单',
      '  最小权限 | 及时补丁 | 关无用服务 | 改默认口令 |',
      '  SSH 禁密码登录用密钥 | 防火墙白名单 | 日志审计 | 备份',
    ],
  },
  {
    n: 6, title: '恶意软件手册',
    lines: [
      '══ 类型',
      '  病毒/蠕虫/木马/勒索/挖矿/间谍/Rootkit/无文件攻击',
      '  下载器: 先小后大, 再拉真正载荷',
      '',
      '══ 静态分析 (不运行)',
      '  file: 类型 (PE/ELF/脚本)  |  strings: 可读字符串',
      '  hexdump: 原始字节  |  反汇编: 读逻辑',
      '  导入表 (PE): 调用了哪些 API → 判断行为',
      '',
      '══ 危险 API 组合 (进程注入)',
      '  VirtualAllocEx (分配内存) + WriteProcessMemory (写入代码)',
      '  + CreateRemoteThread (远程线程执行)',
      '',
      '══ 动态分析 (沙箱)',
      '  观察: 网络连接 (C2)、文件操作、进程、注册表、自启动',
      '  对抗: 恶意软件检测沙箱/虚拟机/调试器, 检测到就装死',
      '',
      '══ 持久化 (常见)',
      '  Windows: Run 键/启动目录/计划任务/服务/DLL劫持/WMI',
      '  Linux: cron/rc.local/LD_PRELOAD/SSH公钥/隐藏账户',
      '',
      '══ 防御',
      '  AV → EDR → 白名单; 不点不明附件; 禁用宏;',
      '  分段 (不扩散); 备份 (抗勒索); 最小权限 (跑不起来)',
    ],
  },
  {
    n: 7, title: '数字取证手册',
    lines: [
      '══ 铁律',
      '  只读镜像 + 哈希校验 + 副本分析 + 完整记录 (可上法庭)',
      '',
      '══ 文件魔数速查',
      '  7F 45 4C 46  ELF  |  4D 5A  PE (MZ)',
      '  FF D8 FF  JPEG  |  89 50 4E 47  PNG',
      '  50 4B  ZIP  |  25 50 44 46  PDF  |  1F 8B  GZIP',
      '  42 4D  BMP  |  47 49 46 38  GIF',
      '',
      '══ 删除与恢复',
      '  删除=标记可复用, 数据还在 → 可恢复 (未覆盖前)',
      '  雕刻 (Carving): 按魔数在镜像里搜文件 (foremost/binwalk)',
      '',
      '══ 分析手法',
      '  strings: 捞可读字符串 (密码/URL/聊天)',
      '  hexdump: 字节真相 (尾部追加数据、图片 EOF 之后)',
      '  文件尾部: tail 看最后 N 字节',
      '  元数据: EXIF (GPS/时间/设备), 文档作者/修订历史',
      '  隐写: 图片尾部文本、LSB、EXIF 注释',
      '',
      '══ 取证工具',
      '  dd: 镜像  |  Autopsy/SleuthKit: 综合分析',
      '  Volatility: 内存取证 (进程/网络/恶意代码)',
      '  Wireshark: 流量取证  |  7zip/strings: 快速捞',
      '  exiftool: 元数据  |  binwalk: 固件/文件雕刻',
    ],
  },
  {
    n: 8, title: '蓝队与应急响应手册',
    lines: [
      '══ 应急响应六步',
      '  检测 → 分析 → 遏制 → 根除 → 恢复 → 复盘',
      '  遏制 > 根除: 先隔离再慢慢查',
      '',
      '══ 日志关键字段',
      '  认证日志: 时间/IP/用户/成功失败',
      '  Web 日志: 时间/IP/URL/参数/UA/状态码',
      '  看什么: 高频失败+成功、sqlmap UA、UNION/sleep、陌生文件',
      '',
      '══ IoC (失陷指标)',
      '  恶意 IP/域名/URL、文件哈希、进程名、注册表项',
      '  拿到 IoC → 全网排查 → 时间回溯 → 扩展关联 → 形成检测规则',
      '',
      '══ 攻击链视角 (检测点)',
      '  侦察 (扫描特征) → 打点 (漏洞利用日志) →',
      '  权限提升 (sudo/新账户) → 横向 (445/PsExec) →',
      '  数据窃取 (大流量外传) → 痕迹清理 (日志删除)',
      '',
      '══ 防御体系',
      '  纵深防御: 边界 (FW/IDS/WAF) + 主机 (EDR) + 网络 (分段) + 数据 (加密)',
      '  零信任: 不信任内网, 每次访问都验证',
      '  SIEM: 集中日志+规则告警; 关键: 告警要能响应',
      '  演练: 钓鱼演练/应急演练, 平时多流汗战时少流血',
    ],
  },
  {
    n: 9, title: '云与容器手册',
    lines: [
      '══ 云攻击面',
      '  控制台/API 凭据 (AK/SK)、存储桶权限、暴露端口、',
      '  容器逃逸、镜像漏洞、供应链 (被攻破的插件/依赖)',
      '',
      '══ IAM 要点',
      '  最小权限 Policy; 根账户锁死; AK/SK 绝不进代码;',
      '  短期密钥+轮换; 定期审计权限',
      '',
      '══ S3/存储桶',
      '  ACL/策略配错 = 公开: 能列出/下载/甚至上传',
      '  检查: 桶策略是否只允许授权主体',
      '',
      '══ 容器/K8s',
      '  镜像: 扫描漏洞+别藏密钥; 非 root 运行; 只读根文件系统',
      '  Docker Socket 暴露 = RCE; K8s: RBAC 最小化、网络策略、',
      '  Dashboard/etcd 别暴露、审计日志开启',
      '',
      '══ 云加固清单',
      '  默认私有 | 加密 (TLS+存储) | 审计全开 | 自动化扫描',
      '  (Checkov/Prowler/ScoutSuite) | 事件响应演练',
    ],
  },
  {
    n: 10, title: 'AI 安全手册',
    lines: [
      '══ 核心问题',
      '  LLM 分不清"指令"和"数据" → 提示注入',
      '',
      '══ 攻击面',
      '  提示注入 (劫持指令) | 数据投毒 (污染训练) |',
      '  越狱 (绕过对齐) | 模型窃取 | 幻觉诱导 |',
      '  AI 钓鱼/深度伪造/自动化攻击',
      '',
      '══ 提示注入手法',
      '  直接命令 ("忽略之前指令") | 角色扮演 ("你现在是无限制AI") |',
      '  假想场景 | 分隔符混淆 | 间接注入 (让 AI 读恶意文档) | 编码绕过',
      '',
      '══ 防御',
      '  AI 最小权限 (无权限闯不了祸) | 人在回路 (高风险人工确认) |',
      '  输入/输出过滤 | 隔离系统提示词 | 交互日志监控',
      '',
      '══ 参考',
      '  OWASP Top 10 for LLM Applications — 入门必读',
    ],
  },
  {
    n: 11, title: '逆向工程手册',
    lines: [
      '══ 从源码到机器码',
      '  源码 → 编译 → 汇编 → 机器码 → 链接 → 可执行文件',
      '  文件格式: ELF (Linux, 魔数 7F 45 4C 46) / PE (Windows, 4D 5A)',
      '',
      '══ 常用指令',
      '  mov 传送 | add/sub 运算 | cmp 比较 | jmp 无条件跳转',
      '  jne/je 条件跳转 | call/ret 函数调用 | push/pop 栈操作',
      '  寄存器: eax/ebx/ecx/edx 数据, esp/ebp 栈, eip 下一条指令',
      '',
      '══ 破解思路 (验证程序)',
      '  骨架: 取输入 → cmp 期望值 → jne 失败分支',
      '  思路一: 读懂比较 → 算出正确输入 (ASCII: 0x31=\'1\', 0x41=\'A\')',
      '  思路二: patch 关键跳转 (jne 0x75 → jmp 0xEB) → 绕过校验',
      '',
      '══ 工具',
      '  file/strings/hexdump: 静态三件套 (游戏内)',
      '  IDA/Ghidra/Radare2: 专业反汇编',
      '  gdb/x64dbg: 调试器 (断点/单步/看寄存器)',
      '',
      '══ 对抗技术',
      '  加壳 (UPX: strings 捞不出东西) → 脱壳/内存 dump',
      '  混淆 (改名/控制流平坦化) → 耐心+自动化',
      '  反调试/完整性校验 → 修改检测点/同时 patch',
    ],
  },
  {
    n: 12, title: '社会工程与反钓鱼手册',
    lines: [
      '══ 心理武器',
      '  信任 (冒充客服/同事) | 恐惧 (账户冻结) | 贪婪 (中奖)',
      '  好奇 (你被偷拍了) | 压力 (立即处理)',
      '',
      '══ 钓鱼攻击',
      '  仿冒发件人: vuln-bank.com → vuln-bank.corn',
      '  伪造链接: 显示 bank.com 实际指向钓鱼站',
      '  附件投毒: Word 宏下载木马',
      '  克隆官网: 输入什么都被记录',
      '  鱼叉钓鱼: 针对个人定制, 成功率更高',
      '',
      '══ 识别钓鱼邮件 (自查清单)',
      '  1. 域名是否官方 (带 -secure/-support/拼写变体 = 可疑)',
      '  2. 是否制造紧迫感 ("立即""否则冻结")',
      '  3. 是否索要凭据/验证码',
      '  4. 链接悬停看真实 URL',
      '  5. 通过官方渠道二次核实',
      '',
      '══ 其它社工手法',
      '  电话借口 (pretexting)、USB Drop、伪基站短信、QR 钓鱼、尾随',
      '',
      '══ 防御',
      '  验证码绝不给任何人 | MFA 兜底 | 官方渠道核实 |',
      '  企业: 钓鱼演练 + 邮件认证 (SPF/DKIM/DMARC) + 异常监控',
    ],
  },
  {
    n: 13, title: '无线安全手册',
    lines: [
      '══ 加密演进',
      '  WEP (几分钟可破) → WPA (TKIP 有漏洞) →',
      '  WPA2 (主流, 可离线字典) → WPA3 (SAE 抗离线爆破)',
      '',
      '══ WPA2 破解流程',
      '  deauth 踢下线 → 抓四次握手 → 离线跑字典',
      '  工具: aircrack-ng + hashcat; 弱密码 (12345678) 秒破',
      '',
      '══ 其它攻击',
      '  Evil Twin: 同名假热点 → 中间人/钓鱼页',
      '  WPS PIN: 8 位可暴力, 关闭它',
      '  开放网络: 流量裸奔, 敏感操作必上 VPN/HTTPS',
      '',
      '══ IoT 风险',
      '  默认口令 (Mirai 僵尸网络: 61 个默认口令打天下)',
      '  不更新固件 | Telnet 后门 | 摄像头被控',
      '',
      '══ 家庭加固',
      '  WPA2/WPA3 + ≥12 位密码 | 关 WPS | IoT 隔离网段 |',
      '  关 UPnP/远程管理 | 定期检查连接设备',
    ],
  },
  {
    n: 14, title: '渗透测试方法论手册',
    lines: [
      '══ PTES 七阶段',
      '  前期交互(授权范围) → 情报收集(OSINT) → 威胁建模 →',
      '  漏洞分析 → 渗透利用 → 后渗透 → 报告',
      '',
      '══ OSINT 渠道',
      '  搜索引擎 (Google dorking) | DNS/证书透明日志 (crt.sh)',
      '  GitHub 代码泄露 | 招聘信息 (技术栈) | 社交媒体',
      '  Shodan/Fofa (暴露资产扫描)',
      '',
      '══ 报告结构',
      '  执行摘要 (高层) → 范围方法 → 发现清单',
      '  (每项: CVSS 评分 + 复现步骤 + 影响 + 修复建议) → 附录',
      '  写不清复现步骤 = 没用的报告',
      '',
      '══ 伦理与法律',
      '  只测授权目标 | 不破坏不窃取 | 负责任披露 |',
      '  无授权 = 违法 (网络安全法/刑法 285-287 条)',
      '',
      '══ 证书路径 (参考)',
      '  OSCP (实战) / CEH / CISSP (管理) / CISP (国内) /',
      '  PNPT / eWPT (Web) / CRTO (红队)',
    ],
  },
  {
    n: 15, title: '扩展领域速览',
    lines: [
      '══ 移动安全',
      '  APK/IPA 逆向: jadx/apktool 反编译, 找硬编码密钥/不安全存储',
      '  常见漏洞: 明文日志、弱加密、证书校验绕过、Root 检测绕过',
      '',
      '══ 工控安全 (ICS/SCADA)',
      '  PLC/SCADA 协议 (Modbus/S7comm) 大多无认证',
      '  攻击: 震网 (Stuxnet) 是教科书案例',
      '  防御: 物理隔离 (Air Gap) + 工控防火墙 + 白名单',
      '',
      '══ 车联网安全',
      '  攻击面: OBD 接口、CAN 总线、无钥匙进入 (中继攻击)、',
      '  车载娱乐系统、云端 APP',
      '  知名案例: 2015 Jeep Cherokee 远程接管 (Uconnect)',
      '',
      '══ 供应链安全',
      '  typosquatting (恶意包伪装: lodash vs lodahs)',
      '  npm/pip 投毒 | CI/CD 管道劫持 | 依赖漏洞 (SCA 扫描)',
      '',
      '══ 量子与后量子',
      '  量子计算威胁 RSA/ECC (Shor 算法)',
      '  后量子密码 (PQC): 美国 NIST 已标准化 (Kyber/Dilithium)',
      '',
      '══ 区块链安全',
      '  智能合约漏洞 (重入攻击/整数溢出)、私钥管理、',
      '  51% 攻击、预言机操纵',
    ],
  },
];

const DOC_APPENDIX = [
  {
    n: 'A', title: '游戏命令速查',
    lines: [
      '  状态: help / mission / hint / learn / status / levels / map',
      '  学习: course <n> <章> | quiz <n> | demo <主题> | docs <章> | docs term <词>',
      '  挑战: challenge <n> | submit <flag或答案> | ai <内容> | board | mistakes',
      '  任务: scenario <编号|main> (扩展场景) | next | mission',
      '  靶场: lab | lab get <文件> | lab exec <命令> | lab read <路径> | browser',
      '  界面: theme <名称> | panel on|off | guide (新手引导) | export (学习报告)',
      '  文件: ls / cat <文件> / file <文件> / strings <文件> / tail <文件> / hexdump <文件>',
      '  工具箱: tools (tools <命令> 看手册)',
      '  密码: b64 -d|-e / rot13 / caesar -s <位移> / vig -e|-d -k <密钥>',
      '        xor -k <密钥> / md5 / sha256 / crack <哈希>',
      '  流程: start / resume / save / reset / sound on|off / clear / credits',
      '  提示: Tab 补全命令/文件; help <关键词> 检索',
    ],
  },
  {
    n: 'B', title: '端口速查',
    lines: [
      '  21 FTP   22 SSH   23 Telnet   25 SMTP   53 DNS',
      '  80 HTTP   110 POP3   135 RPC   139 NetBIOS   143 IMAP',
      '  443 HTTPS   445 SMB   993 IMAPS   995 POP3S',
      '  1433 MSSQL   1521 Oracle   2049 NFS   2222 SSH备用',
      '  2375 Docker   3000 Web   3306 MySQL   3389 RDP',
      '  5432 PostgreSQL   5900 VNC   6379 Redis   8080 代理',
      '  8443 HTTPS备   9200 Elasticsearch',
      '  后门高危: 1337 / 31337 / 4444 / 666 / 6666',
    ],
  },
  {
    n: 'C', title: '魔数速查',
    lines: [
      '  7F 45 4C 46   ELF 可执行 (Linux)',
      '  4D 5A          PE 可执行 (Windows, MZ)',
      '  FF D8 FF       JPEG 图片',
      '  89 50 4E 47    PNG 图片',
      '  47 49 46 38    GIF 图片',
      '  42 4D          BMP 图片',
      '  50 4B          ZIP 压缩包',
      '  25 50 44 46    PDF 文档',
      '  1F 8B          GZIP 压缩',
      '  23 21          #! 脚本 (shebang)',
    ],
  },
  {
    n: 'D', title: '术语表 (docs term <词> 查询)',
    lines: [
      '  输入 docs term <关键词> 可查 40+ 条术语定义。',
      '  常用词: SQL注入 / XSS / CSRF / SSRF / IDOR / CVE / C2 / IoC /',
      '  RCE / 提权 / 横向移动 / 持久化 / 沙箱 / 加盐 / 彩虹表 /',
      '  MFA / VPN / WAF / EDR / SIEM / OSINT / 社工 / 钓鱼 /',
      '  提示注入 / 深度伪造 / 零信任 / 蜜罐 / 隧道 / 代理',
    ],
  },
];

const GLOSSARY = [  { term: 'sql注入', def: 'SQL Injection: 用户输入拼进 SQL 语句改变查询逻辑。' },
  { term: 'xss', def: '跨站脚本: 输入被原样渲染, 脚本在受害者浏览器执行。' },
  { term: 'csrf', def: '跨站请求伪造: 诱导浏览器带 Cookie 向目标发请求。' },
  { term: 'ssrf', def: '服务端请求伪造: 让服务器访问攻击者指定的地址。' },
  { term: 'idor', def: '不安全的直接对象引用: 改 id 越权访问他人数据。' },
  { term: 'cve', def: '公开漏洞编号: CVE-2021-1234, 全球统一漏洞标识。' },
  { term: 'c2', def: '命令与控制服务器: 恶意软件收指令/回传数据的服务器。' },
  { term: 'ioc', def: '失陷指标: 恶意IP/哈希/URL 等"已被入侵"的证据。' },
  { term: 'rce', def: '远程代码执行: 攻击者在目标机器上执行任意命令。' },
  { term: '提权', def: '权限提升: 从低权限获得更高权限 (root/SYSTEM)。' },
  { term: '横向移动', def: '横向移动: 从一台被控机器跳到同网络其它机器。' },
  { term: '持久化', def: '持久化: 恶意软件让自身在重启/重装后仍能存活。' },
  { term: '沙箱', def: '沙箱: 隔离环境, 安全运行恶意样本观察行为。' },
  { term: '加盐', def: 'salt: 密码哈希前附加随机串, 使彩虹表失效。' },
  { term: '彩虹表', def: '彩虹表: 预计算的"密码→哈希"表, 加速破解。' },
  { term: 'mfa', def: '多因素认证: 密码+设备/生物特征等多重验证。' },
  { term: 'vpn', def: '虚拟专用网络: 加密隧道, 远程安全接入内网。' },
  { term: 'waf', def: 'Web 应用防火墙: 拦截 SQLi/XSS 等 Web 攻击。' },
  { term: 'edr', def: '端点检测响应: 终端行为检测与自动处置。' },
  { term: 'siem', def: '安全信息与事件管理: 集中日志+规则告警。' },
  { term: 'osint', def: '开源情报: 从公开渠道收集目标信息。' },
  { term: '社工', def: '社会工程: 利用人的心理弱点而非技术漏洞。' },
  { term: '钓鱼', def: 'phishing: 伪造邮件/页面诱导泄露信息或安装木马。' },
  { term: '提示注入', def: 'Prompt Injection: 输入劫持 LLM 指令, 泄露机密/执行操作。' },
  { term: '深度伪造', def: 'Deepfake: AI 生成的逼真假视频/语音, 用于诈骗/造谣。' },
  { term: '零信任', def: 'Zero Trust: 不信任任何网络位置, 每次访问都验证。' },
  { term: '蜜罐', def: 'Honeypot: 伪装的目标, 引诱并记录攻击者行为。' },
  { term: '隧道', def: 'Tunneling: 把流量封装进另一种协议 (DNS/ICMP隧道)。' },
  { term: '代理', def: 'Proxy: 中转流量, 隐藏来源/绕过访问控制。' },
  { term: '反弹shell', def: 'Reverse Shell: 目标主动连回攻击机, 绕过防火墙。' },
  { term: '后门', def: 'Backdoor: 绕过正常认证的隐蔽入口。' },
  { term: '漏洞利用', def: 'Exploit: 针对特定漏洞的攻击代码/手法。' },
  { term: '0day', def: '0day: 厂商尚不知晓/未修复的漏洞。' },
  { term: '勒索软件', def: 'Ransomware: 加密文件勒索赎金的恶意软件。' },
  { term: '木马', def: 'Trojan: 伪装成正常软件的恶意程序。' },
  { term: '蠕虫', def: 'Worm: 自我复制通过网络传播的恶意程序。' },
  { term: 'rootkit', def: 'Rootkit: 深度隐藏自身痕迹的恶意工具。' },
  { term: '哈希传递', def: 'Pass-the-Hash: 用密码哈希直接认证, 无需明文。' },
  { term: '中间人', def: 'MITM: 攻击者插入通信双方之间窃听/篡改。' },
  { term: '蜜罐邮件', def: '钓鱼演练: 企业模拟钓鱼邮件统计点击率。' },
];

/* 手册章节 → 对应课程 (docs 速查, course 深读) */
const DOC_COURSE_MAP = {
  1: 'course 12 (方法论) / course 9 (蓝队)',
  2: 'course 1 (网络与侦察)',
  3: 'course 2 (密码学)',
  4: 'course 3 (Web 安全)',
  5: 'course 6 (权限提升)',
  6: 'course 10 (恶意软件)',
  7: 'course 5 (数字取证)',
  8: 'course 9 (蓝队)',
  9: 'course 11 (云安全)',
  10: 'course 13 (AI 安全)',
  11: 'course 4 (逆向工程)',
  12: 'course 7 (社会工程)',
  13: 'course 8 (无线安全)',
  14: 'course 12 (渗透方法论)',
  15: '— (扩展领域速览)',
};

GLOBAL_COMMANDS['docs'] = (toks) => {
  const arg = (toks[1] || '').toLowerCase();
  if (arg === 'term') {
    const kw = toks.slice(2).join(' ').toLowerCase();
    if (!kw) { T.print('用法: docs term <关键词> — 查术语表', 'info'); return; }
    const hits = GLOSSARY.filter((g) => g.term.includes(kw) || g.def.toLowerCase().includes(kw));
    if (!hits.length) { T.print(`术语表中没有找到 "${kw}"。`, 'error'); return; }
    T.print(`═══ 术语表: ${kw} ═══`, 'header');
    hits.forEach((g) => T.print(`  ${g.term} — ${g.def}`, 'cmd'));
    return;
  }
  if (arg === 'search') {
    const kw = toks.slice(2).join(' ').toLowerCase();
    if (!kw) { T.print('用法: docs search <关键词> — 全文检索', 'info'); return; }
    T.print(`═══ 检索: "${kw}" ═══`, 'header');
    let count = 0;
    DOCBOOK.concat(DOC_APPENDIX).forEach((ch) => {
      ch.lines.forEach((l) => {
        if (l.toLowerCase().includes(kw) && count < 24) {
          T.print(`  [第${ch.n}章 ${ch.title}] ${l.trim()}`, 'cmd');
          count++;
        }
      });
    });
    if (!count) T.print('没有找到相关内容。', 'dim');
    return;
  }
  const n = parseInt(toks[1], 10);
  if (!n) {
    T.print('═══ 安全知识手册 ═══ (小型教材 · 随时查阅)', 'header');
    DOCBOOK.forEach((ch) => T.print(`  [${String(ch.n).padStart(2, ' ')}] ${ch.title}`, 'cmd'));
    DOC_APPENDIX.forEach((ch) => T.print(`  [${ch.n}] ${ch.title}`, 'cmd'));
    T.print('用法: docs <章节号> 阅读 ｜ docs term <词> 查术语 ｜ docs search <词> 检索', 'cmd');
    return;
  }
  const ch = DOCBOOK.find((x) => x.n === n);
  if (!ch) { T.print('章节编号无效 (1-' + DOCBOOK.length + ' 或附录 A-D)。', 'error'); return; }
  T.print(`═══ 第${n}章 ${ch.title} ═══`, 'header');
  ch.lines.forEach((l) => T.print(l, 'normal'));
  const linked = DOC_COURSE_MAP[n];
  if (linked && linked !== '—') T.print(`关联课程(深读): ${linked}  (本手册为速查版)`, 'dim');
  T.print('── 本章完 (docs term <词> 查术语; docs <下一章> 继续) ──', 'dim');
};
GLOBAL_COMMANDS['docs'].usage = 'docs [章节|term <词>|search <词>] — 安全知识手册';
